# Generated by Django 4.2.28 on 2026-03-02 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSubmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=50)),
                ('dept_ppt', models.CharField(db_index=True, max_length=300)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('editing', 'Editing'), ('submitted', 'Submitted')], default='not_started', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bsa_submission_status',
                'unique_together': {('version', 'dept_ppt')},
            },
        ),
    ]
